### ISSUE TITLE
getting an error `Two or more files with the name ".DS_Store" exist in the root folder.`

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#19]
it would be great to be able to 'exclude' files ... as .DS_Store (mac) files are definitely not something that matter for exports.

`Two or more files with the name ".DS_Store" exist in the root folder.`

**Comment by dwrolvink** [comment]
Hi @jcolson 

Good idea, I had already added the .obsidian folder in the code some time back because it gave issues. I was intending to add this to the config yaml.

This should be solved by: https://github.com/obsidian-html/obsidian-html/commit/1659b6e4d449d55bbc78ed378d3b3400fbf10d0e

See the documentation here: https://obsidian-html.github.io/Resources/Example%20site/esExclude%20subfolders.html

Let me know if you can use this to solve that error.

**Comment by jcolson** [comment]
this works like a champ ... also allows to ignore `.trash`, and I have a 'mobile obsidian profile' that i call `.obsidian-mobile` ... so this all works well!  cheers
