### ISSUE TITLE
relative links instead go to drive root in HTML export

### ISSUE THREAD

**Issue by NireBryce** [obsidian-html/obsidian-html#192]
(in PyPI package, so either it's already fixed but needs pushing, or isn't fixed yet)

At least on Windows, all the links in index.html lead to `<a href="/obs.html/tags/` and `<img src="/attachments/foo.png"`

This looks like a typo (missing the `.` in `./` to make it relative), which makes it think that's a folder on the root drive.

you can fix it with find and replace in the html (just watch out for `"/ RSS`, a false positive), but I think it's either a typo in obsidian-html, or a typo/unintended-use  in one of the libraries it depends on.  If I remember I'll go digging this week.

**Comment by dwrolvink** [comment]
The html is compiled intended for use on a webserver (otherwise the javascript page-fetching wouldn't work anyways). 
If your html output folder is e.g. 'C:\Users\Foo\Documents\html', then running:
``` powershell
python -m http.server --directory 'C:\Users\Foo\Documents\html'
```
Should serve the website. Then going to http://localhost:8000 in the browser should give you your website, and the `/` should then point to your webroot, not the disk root.

You could add the `.` in by setting `html_url_prefix: '.'` in the config.yml, but if you have notes in a folder structure, that won't work well. (It might work if you only open the index.html, but not if you open a link in a new tab). 

I'd suggest just running the server, you can do that in a separate terminal and leave it running while you work.

Let me know if this solves your issue, and if I understood your problem correctly. 

If you are really deadset on using the html without a webserver then I could add a mode that just uses the relative paths from the markdown directly, but I do believe that the whole note tab mechanism won't work without a server, so you can only have one note open at a time then.

**Comment by dwrolvink** [comment]
Okay, the graph view won't work at all then:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/foo/git/obsidian-html.github.io/obs.html/data/graph.json. (Reason: CORS request not http).```
```
It does open the links, but any file in a folder will have faulty links to the css files i.a.
So for that we'd need to add another setting that will use relative paths for html and disable unsupported features like graph view

**Comment by dwrolvink** [comment]
Maybe you can have a look at https://github.com/obsidian-html/obsidian-html/tree/relative_html

You can install and use this branch via this method: https://obsidian-html.github.io/Instructions/Run%20custom%20code.html
After the `cd obsidian-html` step, do `git checkout relative_html` and then continue.

You also need to add the following to your config.yaml to enable this mode:
``` yaml
toggles:
  # Whether the html paths will be relative. 
  # Note: This is only useful if you want to open the html locally on your machine without using a webserver
  #  and is generally not advised. This will also disable all features that need a webserver to function
  #  such as the graph view.
  relative_path_html: True
```
(If you already have the `toggles` section, just place relative_path_html under it).

I've tested this on my machine, and it already works pretty well. 

If you need more help let me know.

**Comment by dwrolvink** [comment]
Thanks for the feature request, this was a nice rabbit hole to dive into.

Although the feedback can be considered lacking, I do think personally the feature is ready for release, and so I've just gone ahead and added it to version 1.2.0.

Read more here:
- https://obsidian-html.github.io/Changelog/v1.2.0.html
- https://obsidian-html.github.io/Configurations/Relative_path_html.html
