### ISSUE TITLE
[Feature Request] - Improved Graph View

### ISSUE THREAD

**Issue by dr-code** [obsidian-html/obsidian-html#211]
Hello!

I was wondering if it would be possible to do a graph view like the one on this Gatsby template. https://gatsby-project-kb.vercel.app/features/graph-view (top right corner)

Thanks!

**Comment by dwrolvink** [comment]
# Graph view
When you click on the graph button below a note it show the graph view, you can zoom in and pan around, if the nodes are too close together you can set [coalesce_force](https://obsidian-html.github.io/Configurations/Graph%20view.html).

![image](https://user-images.githubusercontent.com/30291690/163001764-c75c9544-df44-4404-806d-a801e53ddb02.png)

Did you find this feature already, and if so, in what way would you like it to be more like the graph view that you showed?

# TOC/Contents
Short answer: no.

There is a content page for the whole site, you can access it by clicking the little tree icon in the top right of the screen, you then get to a page like so: https://obsidian-html.github.io/obs.html/dir_index.html

You can also set this to be your homepage so that it will always show on the left of the screen.

To mimick the layout of https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/ (which I do like a lot btw), we would need to do a couple of things:

- Set no tabs
  ``` yaml
  toggles:
    no_tabs: True
  ```
- add a setting to add the dir_index on the right, and highlight the current page
- add a TOC generator (perhaps there is some off the shelf tool that can do that for us), and then format that to the correct html code and also add it to the page outputs, but then on the right

I think that is a nice idea and we should make a separate issue for that, as now we have two different ones in one issue, which is messy.

Love to hear your thoughts on this.

**Comment by dwrolvink** [comment]
one issue is that the no_tabs feature kind of stretched the current layout system to its limit, so adding this in will require a complete rewrite of the templating system, which will take some time, so don't expect quick progress on this feature request.

**Comment by dr-code** [comment]
I will create a different issue for the TOC request.

As far as the graph goes: I have already played around with the coalesce_force.
One thing I liked about the graph on that link is the focused aspect, where it highlights the direction of the connection while zooming into that specific connection. I have attached a video:

https://user-images.githubusercontent.com/8603561/163017470-a735dcef-474d-46ee-8e1a-bba163b836a1.mov

**Comment by dwrolvink** [comment]
I can probably add arrows to denote direction, but anything beyond that is out of scope for me. I might add some mechanism to provide the code that is used to create the graph, but that is not an easy system to use, especially not for beginners.

For anybody else reading this, I am open to PRs that implement this kind of graph as an option, be it through the current graph library or a different one, as long as it (re)uses the graph.json file.

**Comment by dr-code** [comment]
I think I found the source of it. its called Note-Graph. https://www.npmjs.com/package/note-graph

Not sure if that helps. I agree definitely not something for me as a beginner.

**Comment by dwrolvink** [comment]
Try out the latest code, I've added the beginnings of a template system for the graph view, so that anyone can add their own custom code.

At the moment the custom code is not working yet, but there are two default templates already.

If you add this to your config.yml, then you get an approximation of what you wanted:
``` yaml
toggles:
  features:
    graph:
      template: 2d            # "2d", "3d"
```

Still working on adding the note-graph as-is, then you would get exactly what you wanted, but it accepts a different data filestructure than what d3.js (what I used previously) and force-graph (what note-graph uses as a dependency) accept. 

I've opted to use force-graph for the new templates because it is super nice compared to d3.js. The default 3d template looks super cool, but I am still undecided on its usability.

Anyways, will add a second data file with the correct structure for note-graph and then I can add that in and see how it looks, maybe make it a default template, then I'll add in the functionality that users can load in their own custom code and then publish it in a new release.

Any feedback is welcome, then I can keep it in mind while I'm building the code.

**Comment by dwrolvink** [comment]
``` yaml
toggles:
  features:
    graph:
      template: node_graph            # "2d", "3d"
```

Try that for node_graph integration. Notice there is also a full page graph now, which you can open by clicking the graph icon in the top right.

> Don't forget to pull the latest git changes like before.

Node graph is a bit poorly documented. I made an issue for this, but as it stands I cannot give any further support on tweaking node-graph. It just takes me too much time for too little return value.

Try out the 2d option that I posted earlier. This is already pretty similar to node-graph, and it is way better documented, and since it integrates more transparently with d3, it is way more powerful out of the box. (Which makes more sense for me to invest my time in because it can fill in way more use cases than node-graph can at the moment).

**Comment by dr-code** [comment]
I tried both 2d and node_graph, both are awesome. I see the issues with node_graph, like you cannot click on the node and it take you to the page or once you click on it, it almost adds to the connections.

I do like 2d though, very visually appealing. I think that if the 2d option is more powerful out of the box that’s the one we go with.

**Comment by dwrolvink** [comment]
Yes there were some integration issues with node-graph, but if clicking on a node does not bring you to the page, that is a bug. Clicking around yesterday evening with different configurations I already found and fixed some bugs, but I'm sure there are more.

Let's go with the 2d version instead then. This will allow me to clean up a fair bit of code that I had to add to get node-graph working. 

Since now custom graph templates are possible, you might be able to tweak it further if you want to. See also https://github.com/vasturiano/force-graph for examples/docs.
I will write a documentation soon on how the templating works. But if the default 2d is sufficient then of course you don't have to bother with that. 

Note that if you want to just click on a node and see the links light up, you can open the full page graph view (icon top right). Right clicking sends you to the page instead of left clicking in that view.

**Comment by dr-code** [comment]
Yeah the 2d version looks great. And the full page graph view is awesome!

This template of yours is essentially starting to become the become the best of each of the options out there, which im super excited about! strong work!

**Comment by dwrolvink** [comment]
Update: this is basically done. 

- [Documentation has been written](https://obsidian-html.github.io/Configurations/Styling/Writing%20a%20custom%20graph%20view%20template.html)
- I've tested it out on all the layouts, found and fixed some bugs
- Cleaned up the code

I'm going to wait with a new release until we've got the copytree thing figured out and maybe finally do some testing on Windows to really go bug hunting for once. 

So yeah tl;dr: this issue is done but I'm keeping it open until a release is out.

**Comment by dwrolvink** [comment]
oh btw the latest master version now has automatic zooming enabled :D 
the note-graph developer helped me to understand how that stuff works in force-graph, pretty nice effect

right-clicking on the small graph view now also selects notes, so you can link surf there too with the zooming effect, really nice

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Changelog/v2.1.0.html
