### ISSUE TITLE
[Feature Request] - MkDocs

### ISSUE THREAD

**Issue by dr-code** [obsidian-html/obsidian-html#222]
Since you have moved toward a documentation type of note styling, and since you said you did like the Material for MkDocs theme (https://squidfunk.github.io/mkdocs-material/), I was wondering if it would be possible to add some more features from that theme. I didn't know if you wanted me to create a feature request for each or type them here. 

https://squidfunk.github.io/mkdocs-material/reference/
List: Abbreviations, admonitions, annotations, buttons, code blocks, content tabs, data tables, diagrams, footnotes, formatting, grids, icons/emojis, images, lists, mathjax.

I'm sure a lot of this can already be done with obsidian.

Also side note, if its okay with you I'd like to share your project with the Obsidian Publish alternatives showcase: [https://forum.obsidian.md/t/obsidian-publish-alternatives/22886](url)

**Comment by dwrolvink** [comment]
Those are some nice features. I do want to stay close to what Obsidian is/does though. So for example the buttons, there is a plugin for that, but it is unclear to me how many people use this / want buttons to work in the html output.

So I'd rather get an actual use-case that someone has and fill that in, than to reach some kind of feature parity with mkdocs, which seems to do what it does pretty well.

**Comment by dr-code** [comment]
It absolutely does, issue is going from obsidian to mkdocs isn't very smooth. Your code is the smoothest that I have tried.

**Comment by dwrolvink** [comment]
Thanks :)

Yeah the whole Obsidian experience to build the docs is very nice, as we all know, so it might make sense to get more features like those from mkdocs. 

My time is limited though, and the new features have created quite some technical debt, out of date documentation, and there are probably lots of bugs introduced that I haven't found yet. So I'm going to focus on that and wait on a feature request that people are actually really itching for, instead of adding more features just because someone might like to use it in the future :) 

I also still have the graphical installer on my backlog which might be very useful to onboard people that are not that savvy on the command line. 

So I'm closing this for now.
