### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by vaclavstepan** [obsidian-html/obsidian-html#276]
I'm trying to convert the vault on a Mac, Python 3.9.6, with last obsidianhtml from pip, e.g. 2.3.1.
It fails with following error on vaults using Citations plugin. Apparently, the trouble is that Citations uses form of `@citekey` to construct file name - and then I've links there such as [[@whateverbook]]. But that makes @ at scalar start and breaks the yaml run. Could this be escaped?

`
a@b Obsidian-html % obsidianhtml -i config.yaml
> COPYING VAULT /Users/vaclav/Documents/Obsidian-html/KB TO /var/folders/bv/8vznpc0d5f1640jh932ydwz80000gn/T/tmpidkqpzkh
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/private/var/folders/bv/8vznpc0d5f1640jh932ydwz80000gn/T/tmpidkqpzkh/Home.md)
Traceback (most recent call last):
  File "/opt/homebrew/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 662, in main
    recurseObisidianToMarkdown(ep, pb)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  [Previous line repeated 1 more time]
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 56, in recurseObisidianToMarkdown
    md = MarkdownPage(pb, fo, 'note', files)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/MarkdownPage.py", line 44, in __init__
    self.metadata, self.page = frontmatter.parse(f.read())
  File "/opt/homebrew/lib/python3.9/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/opt/homebrew/lib/python3.9/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 54
`

**Comment by dwrolvink** [comment]
There is currently no way to escape anything, as the note is loaded and the frontmatter is parsed in one go, as shown in the error line: `self.metadata, self.page = frontmatter.parse(f.read())`. 

This of course can be added in the next release, if you can share an example frontmatter yaml that causes this error, then we can maybe purge out those kind of keys and then load the yaml, instead of in one go like now.

(We had this kind of error not so long ago with something else, weird that the Obsidian ecosystem has so many instances of invalid yaml in the frontmatter...)

**Comment by dwrolvink** [comment]
no feedback given, closing

**Comment by vaclavstepan** [comment]
Sorry, didn't see the ping for feedback. I revisited the issue, turned out that Citation plugin writes yaml frontmatter, that can include multiple ':' as in example below. This will get correct, once : after the Republic is removed. Similarly, if the title includes single quote, it fails, etc. Maybe it's a Citation plugins trouble?

```
---
title: Effective dose assessment for workers in caves in the Czech Republic: experiments with passive radon detectors
authors: L. Thinova, I. Burian
year: 2008
---
```

**Comment by dwrolvink** [comment]
When I use a colon in the title then Obsidian complains to me about invalid yaml
![image](https://user-images.githubusercontent.com/30291690/175779863-a0f3f82a-5fec-4b77-a60d-3a9fb5067d07.png)
![image](https://user-images.githubusercontent.com/30291690/175779878-7ff7af77-80fd-4cc4-a8d9-6633a4ffec65.png)

But wrapping the value after `title:` in single or double quotes resolves this, e.g.:
![image](https://user-images.githubusercontent.com/30291690/175780120-8ebc715b-eb0f-4a8e-9a8b-595c21e2450d.png)

This gives:
![image](https://user-images.githubusercontent.com/30291690/175780106-abbedc0e-b158-47d9-9905-1f693fd39d69.png)

Note that I used double quotes to wrap the content because I added a single single quote. If you have a single double quote in your title you should wrap it in single quotes.

In fact, all of these are valid (and work with obsidianhtml):
![image](https://user-images.githubusercontent.com/30291690/175780334-1f9cb623-0205-4351-9d05-381b68e95f55.png)

So I am kind of confused that the plugin would generate yaml that Obsidian itself thinks is malformed? 

We could potentially add a step to wrap values in quotes, but this is kind of hacky and could potentially introduce a lot of new bugs where this seems like an issue with the plugin itself.

**Comment by dwrolvink** [comment]
might this be a solution for you? https://github.com/hans/obsidian-citation-plugin/issues/89#issuecomment-988639174

**Comment by vaclavstepan** [comment]
On yes, you are right, that is the issue. Indeed, the faulty unquoted/unescaped text is generated by the plug-in itself and can be avoided by changing the template.
One option is also not to put the meta data in yaml frontmatter, but in the body. Thank you, I think that it is clear now.

**Comment by dwrolvink** [comment]
Alright super! Let me know if you have any other issues.
