### ISSUE TITLE
Folder notes

### ISSUE THREAD

**Issue by Bipodos** [obsidian-html/obsidian-html#288]
Would it be possible to add content to folders? The Obsidian extension AidenLx's Folder Note (https://github.com/aidenlx/alx-folder-note) has the option of using notes with titles identical as folders, but placed outside folders, as contents of folders. Emanote (https://emanote.srid.ca, https://github.com/EmaApps/emanote) is capable of rendering this feature: its tree allows for folders with content if the name of a folder file and a note file is identical (and both are contained in the same folder).
An example may be found here:
https://inspirativity.zettel.page/aeropress
The source folder includes both a folder titled "Aeropress" and a file titled "Aeropress.md:
https://github.com/srid/inspirativity.zettel.page/tree/master/Equipment
I gave it a try myself to my Obsidian vault: worked w/o problems.

Your project includes search capability in websites which I like very much. I hope adding "Folder Notes" feature would not be difficult.
Marcin

**Comment by dwrolvink** [comment]
Should be doable.

Basically change the directory menu code to hide the folder notes, make folders with folder notes clickable, and indicate when they are clickable. Also change the directory menu code to highlight the folder instead of itself (because the page itself would be hidden in the menu).

Then after that would be the implementation of extra features like folder overview and stuff, which all deserve their own issue I think.

**Comment by dwrolvink** [comment]
Going to focus on releasing a new version coming weekend if time allows, after that I can look into this feature, stay tuned.

**Comment by dwrolvink** [comment]
Alright, sorry it took so long. It's a bit more involved feature than most things that come around, and with the amazing weather there was not much spare time behind the computer.

The first version was added to the master branch just now.
To activate the feature be sure to add the following to your config.yaml:

``` yaml
toggles:
  features:
    folder_notes:
      enabled: True
      placement: 'outside folder'   # 'inside folder' , 'outside folder' 
      naming: 'folder name'           # 'folder name', 'index'
```

Note that only 'outside folder' and 'folder name' are supported as of yet. I saw that https://github.com/aidenlx/alx-folder-note supports different placements and naming schemes, so these will be added soon.

If you let me know how you place your notes then I can add that combination next.

With the current settings it will think that this note is a folder note:
``` 
Changelog/
Changelog.md
```
Note that the note is outside of the folder that it is the folder-note for. In other words they share the same parent folder.

I've chosen to highlight folders that have a folder note as the behavior in the left pane is different: instead of folding open/close the folder it just opens the folder note, and thus telegraphing to the user that something else will happen than normal is a good courtesy imo.

You can see an example on the docs site, note the Changelog folder in the left pane: https://obsidian-html.github.io/

Let me know what you think and how it works for you.

**Comment by dwrolvink** [comment]
The other modes are added now too, very poorly tested still though.

I was using outside folder setting, now I am using inside folder setting. 
Both work fine for me at least.

**Comment by dwrolvink** [comment]
Current state published in https://obsidian-html.github.io/Changelog/v3.1.0.html

**Comment by gpQ4utjefs** [comment]
Hide folder note from sidebar
* When there is a folder note of same name as of its containing folder, name of folder and the name of folder note(which is same as folder itself) both becomes visible in the sidebar/side navigation bar

## What i want
* Only folder should be visible in side navigation bar not the name of file(which is same hence redundant)

**Comment by dwrolvink** [comment]
Hi @gpQ4utjefs try installing the current code in master and then setting the following in your config.yml

``` yaml
toggles:
  features:
    folder_notes:
      enabled: True
      placement: 'inside folder'   # 'inside folder' , 'outside folder' 
      naming: 'folder name'           # 'folder name', 'index'
```

That should fill in your usecase

**Comment by Bipodos** [comment]
Thank you for your work!

I reinstalled obsidian-html from git, and then from dowloaded release obsidianhtml-3.1.0. Both installations succeeded. However, the new version simply does not work: it does not generate a site. There are various warnings and an error message: 
ImportError: cannot import name 'UnescapeTreeprocessor' from 'markdown.treeprocessors' (/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/markdown/treeprocessors.py)
The file does exist, it seems not to contain what it is asked to

Going back to version 2.3.1 makes the program run sucessfully (but obviously, w/o new function).
In new version, even turning off all options in yaml does not help. Generation ends with the same error.

 Did you change requirements for python? I have 3.10.5 installed from macports.

**Comment by dwrolvink** [comment]
I've seen this error before with using venvs. If you use venvs, make sure you run at least `pip install obsidianhtml` **within the env that you are running obsidianhtml in**. If you use a downloaded release, you can run `pip install <location of obsidianhtml-3.1.0.tar.gz>` as well.

Any permutation of `--upgrade` or first uninstalling obsdianhtml might also resolve your issue.
At the heart this is a pip issue in not being able to find the correct packages.

For example, to recreate your error on Windows I do:
``` powershell
pip install obsidianhtml
python -m venv testvenv
.\testvenv
obsidianhtml -i ..\obsidian-html.github.io\__src\config.yml
```

This gives me
```
    from markdown.treeprocessors import UnescapeTreeprocessor
ImportError: cannot import name 'UnescapeTreeprocessor' from 'markdown.treeprocessors' (C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\markdown\treeprocessors.py)
```

To resolve this, within the env, I run pip install obsidianhtml again:
``` powershell
# pip install --pre pythonnet    # only necessary on windows
# pip install lxml               # only necessary on windows / when missing
pip install obsidianhtml
```

Afterwards I can run obsidianhtml without issue

**Comment by dwrolvink** [comment]
Closing because of no feedback, just respond here if you get around to it later, will reopen then
