### ISSUE TITLE
Ignore multiple .gitignore files from submodules

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#289]
I'm switching my personal website over to obsidianhtml and adding different projects as submodules. My vault now has multiple .gitignore files, which I am getting around by enabling duplicate files. It would be great if there was an `exclude_files` field for the entire vault, similar to `create_index_from_dir_structure` feature

**Comment by dwrolvink** [comment]
You might try using [exclude_subfolders](https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!exclude-subfolders)

I know it refers to folders, but the code uses it in the following way:

``` python
if path.resolve().is_relative_to(excl_folder_path):
  # skip file
```

And when I test with a file path instead of a folder path, the is_relative_to() function still works as expected in this situation:
``` python
>>> from pathlib import Path
>>> p1 = Path("/home/user/.bashrc")

# test folder case
>>> p1.is_relative_to("/home/user")
True
# test file case
>>> p1.is_relative_to("/home/dorus/.bashrc")
True 
```

So adding this in your config.yml might solve this issue:
``` yaml
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
  - ".gitignore"
  - "subfolder/.gitignore" # etc
```

I guess it would be a good idea to just add a glob filter pattern or the like to exclude all files that are like "*gitignore*" instead having to add every single path, but that is something for another day I guess.

**Comment by dwrolvink** [comment]
Okay I tried this with my own vault adding a `News.md` in the logs dir and then excluding the original `News.md` and that works as intended. So this should work for your gitignores too.

**Comment by hgrw** [comment]
Nice thanks - I will be able to try this in a few weeks

**Comment by hgrw** [comment]
Thanks - gave it a go and worked okay
