### ISSUE TITLE
MermaidExtension missing 1 required positional argument: 'md_globals'

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#291]
obsidianhtml verision 2.3.1 has no issue generating my documentation. Swapped to 3.0.1 and getting

TypeError: MermaidExtension.extendMarkdown() missing 1 required positional argument: 'md_globals'

Looks like a bug. Config file below. You can pull the project and try yourself: https://gitlab.com/hgrw/mico

You'll need to
1. Install pipenv
2. Install deps using pipenv
3. Activate env using pipenv
4. run obsidianhtml -i config/documentation.yaml

PS - Docker container uploaded to container registry is outdated - fixed container will take another few hours to update.

**Comment by dwrolvink** [comment]
Okay that had me confused for a while.

Turns out that python-markdown has been updated in the mean time (two days ago) and this update has the following to say:
![image](https://user-images.githubusercontent.com/30291690/179395840-11ab7feb-b7bf-4436-b20b-c36962418f28.png)

The md_globals parameter had been deprecated for a while now and were no longer needed so I just removed those from all the extensions and that seems to have fixed it.

Will publish this in a new version (3.0.2) asap.

**Comment by corvusdeinanis** [comment]
> The md_globals parameter had been deprecated for a while now and were no longer needed so I just removed those from all the extensions and that seems to have fixed it.

Thank you! So I'm guessing this error I get will be fixed too, right? 

`TypeError: extendMarkdown() missing 1 required positional argument: 'md_globals'`

**Edit - It is fixed now, it works. Thank you!**

**Comment by dwrolvink** [comment]
Alright version 3.0.2 is out. Let me know if that fixes all the errors for you too

**Comment by dwrolvink** [comment]
> **Edit - It is fixed now, it works. Thank you!**

Nice!

**Comment by hgrw** [comment]
Thanks!
