### ISSUE TITLE
UnboundLocalError: local variable 'code' referenced before assignment

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#294]
https://github.com/obsidian-html/obsidian-html/blob/e620594f6d8090c89aac590e204fee23a54560ac/obsidianhtml/lib.py#L405

Interesting ...

**Comment by hgrw** [comment]
A longer term fix might include some additional regression tests for all toggles

**Comment by dwrolvink** [comment]
ugh I should up my testing game with every setting permutation possible I think lol

**Comment by dwrolvink** [comment]
just adding tests is easier said than done though, as you have toggles for a feature (enable) and then subtoggles so there are very many relevant permutations. But yeah, more regression tests at this point would be good I think.

(though the other error earlier today was not one that could be caught by any regression test mind you...)

**Comment by hgrw** [comment]
Yeah, all permutations are beyond reach - there are too many cool features ;)

**Comment by dwrolvink** [comment]
Okay so this is an interesting one. The `code` variable could be set at 5 places. For this error to show up all the showicon settings have to be false. If 1 of the settings is true then it will populate `code` in the function scope and the error won't pop up. This is an easy fix (line 405 should really be `template = template.replace('{theme_popup}', '')`).

A more pressing issue is that disabling the theme selector icon will cause the page to fail loading because the theme selector div is being queried in the javascript somewhere when loading the page and this then bugs out because it isn't found.

So for now disabling the theme selector is not supported and getting rid of the icon can be done by [adding some custom css](https://obsidian-html.github.io/Configurations/Styling/Edit%20HTML,%20CSS,%20JS.html). 

``` css 
.theme-button {
  display: none;
}
```
Will fix this tomorrow probably, it's just that the js dependency really is silly and should be factored out in a decent way and that will take some time (and warrant some thorough testing :wink: )

**Comment by dwrolvink** [comment]
github closed this one automatically, let me know if something is still not right at your side
