### ISSUE TITLE
White screen when loading page

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#305]
A html code that can be added in header or footer, so that every page have that code.

I have checkout the feature of **html_custom_inclusions:** but the problem with this is: 
- It is in header only
- When re-loading page or going to a new link, it shows a weird transition/white page in between

**Comment by dwrolvink** [comment]
I've made a new issue for the feature request.

Regarding the white page, are you only experiencing this when adding your own code?

### antiflash
This is most likely caused by the antiflash element (which ironically can worsen flashing if improperly configured):
``` html
    <div id="antiflash" style="display: none;"></div>
    <script>
            document.getElementById('antiflash').style.display = 'block';
    </script>
```

This is basically a page spanning div with a solid color background. I've added this because I added dark mode, and when loading a new page it would flash white very rapidly, which was extremely annoying.

Adding this div, which gets immediately disabled when the user theme has loaded, reduced that a lot. Note that the background color can be configured at config path `toggles/features/styling/loading_bg_color` which I set to 
```
toggles:
  features:
    styling: 
      loading_bg_color: '22, 22, 22'
```
for https://obsidian-html.github.io/. Which is a happy medium for both the dark and light mode imo.

### page loading times 
If the issue is more that the blank page lasts for too long, then the issue is the page loading time, especially any js being loaded in before load_theme() is called. 

You could use 
``` js
load_script_on_demand(
    '<script path>', 
    callback_function,
    ['args', 'for', 'the', 'callback', 'function'] // or empty list
)
```  
This function adds a script tag with an onload event that calls the callback. This basically allows the page to continue loading while the script is being fetched. Coincidentally, the script tag is added at *the bottom of the page*, so that might help you there. 

Also for large external js libraries, loading them in in this way greatly reduces lag/flashing.

For reference, the load_script_on_demand function can be found here: https://github.com/obsidian-html/obsidian-html/blob/3e4b75a3764238bcd7662be6cb2bfd10efd78766/obsidianhtml/src/js/obsidian_core.js#L344-L360

It is used here (among other places): https://github.com/obsidian-html/obsidian-html/blob/3e4b75a3764238bcd7662be6cb2bfd10efd78766/obsidianhtml/src/graph/default_grapher_3d.js#L1-L18

**Comment by bhickta** [comment]
Yes white flash appears when adding my own code in the config.yaml. 1st it loads my code in full page with white background then the rest of the page loads. This becomes quite annoying

**Comment by dwrolvink** [comment]
You can try the following options:
- Not add your own code
- Load your own code via the `load_script_on_demand()` function call as described above
- Use a custom template (described below)


### Use a custom template 
#### Export default template
``` bash
# export documentation layout html
obsidianhtml -eht 'C:/Users/nisha/Downloads/template.html' documentation  

#### Customize template
Then open the  'C:/Users/nisha/Downloads/template.html' and remove the following code block:
``` html
        <script>
                document.getElementById('antiflash').style.display = 'block';
        </script>
```

You can also add your javascript in the footer of this custom template file, and then you don't have to use `html_custom_inclusions: []`.

#### Use custom template
Then add the following to your config.yml
``` yaml
# Provide the fullpath to a template file to use instead of standard template. 
# Note that this file must contain at least "{content}" somewhere in the page.
html_template_path_str: 'C:/Users/nisha/Downloads/template.html'
```

This will use the 'C:/Users/nisha/Downloads/template.html' file as a template instead of the default.


> Note that the Windows path that I gave might not work. You might have to use `'C:\Users\nisha\Downloads\template.html'` or `'C:\\Users\\nisha\\Downloads\\template.html'`

**Comment by bhickta** [comment]
Yes this above solution works fine
