### ISSUE TITLE
Tags and sub-tags in one page or in sidebar

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#326]
# Current
* Tags and sub-tags are in different pages
* If one wants to visit a sub-tag, one has to go through all its parents tags page
# Request
* All tags and sub-tags on a same page or/and in a side bar (like heading and pages)
* All sub-tags are collapsible under their parents tags
* Example: 
![image](https://raw.githubusercontent.com/glennflanagan/react-collapsible/HEAD/example/img/example.gif)
# Insipiration
* [tag-wrangler](https://github.com/pjeby/tag-wrangler)

**Comment by dwrolvink** [comment]
Alright I've added a first version that implements a tag page that contains all tags with a folding tree structure, in the same way the directory view works.

Example: https://obsidian-html.github.io/obs.html/tags/index.html

- This page is written to `{url}/obs.html/tags/index.html` by default, and thus overwrites the root index of the old tag-page output. 
- The tag-page button at the top-right thus points to this page.
- This 'page by page' output is still generated because the tag links at the bottom of each note still point to these pages.
- For now I've added [a "View all tags" link at the bottom of those pages](https://obsidian-html.github.io/obs.html/tags/type/instruction/index.html) to point back to the main page. I think that is a nice mix of having a view of just the notes with exactly the same tag, and a view where you can browse through all the tags.

Might add a feature in the future that you open the main tag page with the tag centered from with you came on the main page, (i.e. the same way as how the directory view works). But that is not really a priority right now.

Haven't done much of bughunting yet.
Should be enough for you to try out and see if it fills in your usecase.

Here are the instructions for installing the current master branch code: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html

Let me know if you need further instructions for testing, and let me know what you think of this addition.

**Comment by dwrolvink** [comment]
should be implemented, let me know if you miss anything, closing for now
