### ISSUE TITLE
[Feature Request] Breadcrumbs

### ISSUE THREAD

**Issue by gpQ4utjefs** [obsidian-html/obsidian-html#329]
Adding breadcrumbs for ease of navigation

**Comment by dwrolvink** [comment]
I thought I knew what breadcrumbs were,  like a string of 4 or so urls of last navigated pages, but apparently it is just showing the directories that the user is in? If this is correct, can't you just see that in the directory view on the left?

Could you explain your usecase/feature request a bit more?

**Comment by dwrolvink** [comment]
I've just gone ahead and coded something that should be in the ballpark.

You can see the effect at https://obsidian-html.github.io/
Note that the breadcrumbs interact with the [folder notes setting.](https://github.com/obsidian-html/obsidian-html/issues/288) Without it, the folders are not navigable, and the whole breadcrumbs idea does not work / or will have unexpected results.

First version, expect a lot of bugs.

To enable add the following to your config.yml:
``` yaml
toggles:
  features:
    breadcrumbs:
      enabled: True
```

And [install the master version](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html)

Todo (for my administration):
- Add a url check instead of naively using the node with the same name, this will break for nodes with the same name.
  - Maybe add file path info to node list

**Comment by dwrolvink** [comment]
Closing because of no feedback
