### ISSUE TITLE
Weird split-up of tags from frontmatter

### ISSUE THREAD

**Issue by aquatix** [obsidian-html/obsidian-html#349]
I have a `tags:` line of the form `tags: subject, anotherthing` in the frontmatter of my notes. However, in the footer of the html output of obsidianhtml, those tags get split into the seperate characters of this line, so from my example, it gets put into a list of `s u b j e c t ,   a n o ...`.

I could only find an example in the obsidian-html docs with tags: as a yaml list, but obsidian likes the short, comma-separated list just fine.

Thanks in advance!

**Comment by dwrolvink** [comment]
Can you try 
``` yaml
tags: [subject, anotherthing]
```
instead of 
``` yaml
tags: subject, anotherthing
```
?

The bug here is that the code loops through a string instead of a list, and thus you get a tag for each character.

The issue here is caused by Obisidian not respecting standard yaml rules, otherwise you would run into this in writing the note already.

We have checks on the type of the value though, so that should disallow using a string instead of a list, so that should be fixed.

**Comment by aquatix** [comment]
Hm yeah, making it a yaml/python list gives the correct output in the Tags footer, but I'm not happy with doing that in my frontmatter; it's less human readable and I'd have to do it for hundreds of files.

I wasn't aware that this format wasn't according to yaml spec, that's certainly not helpful. Maybe it can be detected though, and be fixed by obsidian-html itself, maybe in the 'to md' module? Just a suggestion, not sure if I'm the only one with this wish :)

**Comment by dwrolvink** [comment]
Yeah sorry I was just exclaiming my annoyance at Obsidian for breaking with the standard as this has given me numerous headaches (probably at least 10% of all user-bugs are related to it).

You're right in that other people will face this issue, and it's my personal goal to have everything work out of the box just as it does in Obsidian. So this is a good issue.

Some issues cannot be fixed because it causes the frontmatter yaml package that I use to parse the yaml to throw up. (That is, without writing my own yaml parser).
But in this case I can just implement the obsidian behavior.

It seems to split a string value into a list if there is a space and/or comma present, as well as any combination of the two. (Blatantly ignoring wrapping the tags in `'` which should cast it to a string.) Trailing comma's are removed, which could be imitated by:

``` python
tags = self.metadata['tags']
if isinstance(tags, str)):
  if ' ' in tags.strip() or ',' in tags:
    self.metadata['tags'] = [x.rstrip(',') for x in tags.replace(',', ' ').split(' ') if x != '']
```
I will add this later today and test whether it behaves exactly as Obisidian behaves with regards to which tags it recognizes.

Note for self: also cast NoneType to lists while we are at it.

**Comment by aquatix** [comment]
Oh, I'm totally with you on those annoyances :)

Neat, you're right on it. Was thinking about a very similar solution myself, thanks for taking your time to fix this for us mere users :)

**Comment by dwrolvink** [comment]
Alright I've added it to master. Review https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html if you don't know how to install the master code version.

You can close this issue if your issue is fixed through this change. The current master code has a lot of changes so it will probably take some time before it is published on pip (I need to do some thorough testing this time around).

**Comment by aquatix** [comment]
Yes, that seems to work, thanks! I'm fine with running the master code, and will be doing some testing for you ;)

**Comment by dwrolvink** [comment]
You're welcome, happy it works now!
And yes, I really enjoy outsourcing bughunting to my users so thank you :smiley:
