### ISSUE TITLE
Feature request:  Ignore bad links in files

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#452]
Hello, I'd like obsidianhtml to make a best effort at parsing my markdown, but not error out if a bad link is found.  Just ignore that link and keep chugging.  Is this possible?  
In fact, I'd like to be able to specify in a file that no links in it be followed, perhaps with a YAML key.  

Currently, I'm getting an error in parsing: `ERROR: header with title 2022-05-22 was not found`
I'd like obsidianhtml to just ignore that and keep going.

**Comment by dwrolvink** [comment]
Alright, obsidianhtml now just prints `Obsidianhtml: Error: Unable to find section #{section} in {link}` in the place of the inclusion if it fails, instead of exiting the program. This mimicks Obsidian's behavior most closely.

Also, now you can add:
``` yaml
obs.html.tags:
- leaf_note
```

To the frontmatter yaml of a note, and this will cause the links to not be followed for that specific note.
