### ISSUE TITLE
Folder notes inside folder error

### ISSUE THREAD

**Issue by welpdx** [obsidian-html/obsidian-html#481]
When using this feature and having the placement as ``placement: 'inside folder'``, I get this error: 
![img](https://i.imgur.com/diirqY8.png)

Works fine if I place the folder note outside the folder and have the placement ``placement: 'outside folder'``

(btw, tysm for awesome repo!)

**Comment by dwrolvink** [comment]
Hmm I have placement: 'inside folder', and that works just fine for me. So I can't replicate this.
Scratching my head a bit why that would make any difference for this function call.

Could you run the following and share the output?
``` shell
pip show regex
```

I was running version 2022.1.18, upgraded to version 2022.10.31 and both did not give me an error.
You might try to run `pip install regex --upgrade` and see if that fixes your issue.

If not, please upgrade to current master code so that we both at least share the same code:

``` shell
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
```

Another reason might be some funky characters in your folder names, if it is not too personal then sharing the output of running `tree -d` inside your vault might help give me a clue on what is going wrong. '\v' is supposed to mean "vertical tab" so if you either have a literal `\V` in your folder/file names, then that might be the issue, if you are wild enough to have vertical tabs in filenames, then try to remove those and see if the issue persists.

**Comment by welpdx** [comment]
```bash
pip show regex
```
![img](https://i.imgur.com/KNrIe2N.png)
```bash
pip install regex --upgrade
```
![img](https://i.imgur.com/WYAJcow.png)

```cmd
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
obsidianhtml convert -i config.yaml
```
![img](https://i.imgur.com/Xf2JKS4.png)


This is on windows 11 btw. I will try on linux and report back

**Comment by welpdx** [comment]
update: works in linux mint but doesn't work in windows 11... :/

**Comment by dwrolvink** [comment]
oh that is pretty helpful, I'll try to replicate your error on windows, I'm guessing something's up with file paths (backslashes in windows file paths being interpreted as escapes)

**Comment by welpdx** [comment]
update: on windows 11, this regex error no longer occurs. 
However, after `pip install git+https://github.com/obsidian-html/obsidian-html`:
 - on windows 11, the table format is still off.
![img](https://i.imgur.com/Ce0uirz.png)
 - on linux though, the table formatting is fine
![img](https://i.imgur.com/qJF0Wkr.png)

Might be my windows 11 system.

Gonna close this issue for now as it is fixed. Thanks for all your work on it bruv
