### ISSUE TITLE
"create_index_from_tags" doesn't work with inline tags

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#489]
I've been experimenting with the idea of creating a simple blog using obsidianHTML, and thought that nested tags might be a good  solution to this.  So I happily created some test pages with tags like this:

```
    #date/2022/12/16
    #topic/biking
```

I then added the following to my `config.yaml` file:

```
    create_index_from_tags:
      enabled: True
      tags: [date, topic]
```

But no matter what I did, obsidianHTML kept saying `No notes found with the given tags`.  I finally discovered that you have to specify tags in the YAML frontmatter -- inline tags are not supported, even though the documentation includes settings specifically for inline tags.

I really hate using YAML as it clutters up the display of every page in Obsidian (that's one of the big things that attracted me to obsidianHTML in the first place...it doesn't require frontmatter on every page).  Would it be possible to support inline tags as well as YAML frontmatter-defined tags?  Or, at the very least, mention in the docs that only frontmatter tags are supported and not inline tags.  It's really confusing at the moment...

Thanks!

**Comment by erikwestra** [comment]
Also, the above config still doesn't work as it seems you need to list every individual tag value, not just the parent of a nested tag.  I guess I can't create a blog using obsidianHTML after all...any other suggestions for how to do this?

**Comment by dwrolvink** [comment]
First off apologies for the fact that you seem to be hitting your head in rapid succession on "half implemented" features.
In the early phase of ObsidianHtml, there was a veritable flurry of feature requests, such as creating an index from tags. Most of these features have not really had any attention for quite some time. This makes the documentation often misleading. 

For example, when this feature was added, the docs were pretty clear that inline tags were not supported, and thus no one at the time would expect inline tags to work with this feature. But in the mean time inline tag support has been incrementally added, and now most standard features work with inline tags where you would expect it.

Anyhow, I've just added some changes that now allow you to use inline tags, and just choose a parent tag, instead of specifying a specific full tag.

See the example vault for the config/vault I used: https://github.com/obsidian-html/example_vault/blob/6515e529e35cb5debf79f178cfd3eabc4b592268/cat_blog.yml

This gave the the following output:
![image](https://user-images.githubusercontent.com/30291690/208190775-f28eed45-e10c-4a62-9c66-ee6f01c4861c.png)

Let me know how this works for you.

**Comment by erikwestra** [comment]
Hi Dorus,

Thanks -- your latest version does indeed allow the `create_index_from_tags` option to work with inline tags, which is fantastic.

Perhaps I'm misunderstanding how this is supposed to work, but I was expecting the `create_index_from_tags` option to work in the same way as `create_index_from_dir_structure` -- by showing the tags in the left navigation sidebar so you can navigate to pages by tag from that sidebar.  Basically, I was hoping that the contents of `obs.html/tags/index.html` would appear in the sidebar so users can navigate using tags rather than folder structure.

Your example vault includes both options, which I find confusing as I thought you'd either create the index (ie, the thing shown in the left sidebar) using a directory structure, or using tags.  Having both seems strange to me...but clearly I've mis-understood what you mean by an "index" here.

Anyway, is there any way of showing the tag index in the left sidebar?  Sorry, I realise that this is beyond the scope of this ticket, and I'll create another ticket for this if it makes sense.  You've certainly fixed the particular limitation described in this ticket.

Oh, and please don't feel the need to apologise -- I realise I'm pushing the limits of what ObsidianHTML is designed for, and what you've built is absolutely fantastic.  I'm just hoping I can help make it even better.

 - Erik.

**Comment by dwrolvink** [comment]
Alright this requires a short history lesson.
In the beginning there were two feature requests:
- Instead of providing an index page, create one dynamically based on a given list of tags (the first feature)
- Instead of providing an index page, create one dynamically based on the folder structure (the second feature)

At this point, there was no side bar yet. Everything looked (more or less) like [tabs mode](https://obsidian-html.github.io/tabs/index.html). 

Then there came a feature request to add a side paneto show a list of notes that existed in the same folder as the current note. To implement this I repurposed the `create_index_from_dir_structure` feature, where I just fetched the html from this page and cut out the part of interest using javascript.

Since then this has evolved further into now having a `second pass` phase in the python code, where we loop through the generated html one more time and do some cutting and pasting so that the client doesn't have to run a ton of spaghetti-code javascript to generate the directory structure every single page load; but the general idea is still the same.

The way the feature is used for the side pane without per se having to overwrite the index is by setting the default output page path to `/obs.html/dir_index.html` instead of `/index.html`. So this kind of morphed the main use of the `create_index_from_dir_structure` feature to just being a side pane generator, but if you set `rel_output_path: 'index.html'` then you will see the original feature in its full glory.

So quite a lot of development on the `create_index_from_dir_structure` feature, but the `create_index_from_tags` feature was created for a feature request and since then not really visited again, so that is still purely a "create an index page for me" feature.

**Comment by dwrolvink** [comment]
Having said that, nothing stopping us adding the same to the `create_index_from_tags` feature:
- Set the default output path to `/obs.html/tag_index.html`
- Add a sidepane feature, something like:
``` yaml
toggles:
  features:
    side_pane:             # only valid for documentation layout
      left_pane:
        enabled: True
        contents: tag_tree # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs
      right_pane:
        enabled: True
        contents: toc      # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs
```

Then `tag_tree` will just work the same as `dir_tree`, that is, lookup what the configured output path is, load the html from that path and put it in the relevant div.

**Comment by dwrolvink** [comment]
So in short, `index` meant the homepage of the website, i.e. the `/index.html` file. Now it means more generally an index like the index in a book, I guess :man_shrugging:

**Comment by dwrolvink** [comment]
If you use the `create_index_from_tags` in the classic way, but use the tabs layout, you have something like a "tags side pane" on the left, but then you will have a tab navigation website, which isn't suited for everyone of course.

But just floating that idea.
As you can see I created a ticket for you, I think it is a good idea to add.

**Comment by erikwestra** [comment]
Thanks, @dwrolvink -- much appreciated!
