### ISSUE TITLE
Note names in tag side pane are displayed in lowercase

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#513]
Sorry to bombard you with new issues...I found another minor one.

Using the `tag_tree` sidebar, I can see a list of tags and their associate note names -- but for some reason the note names are rendered in lowercase.  For example:

<img width="1125" alt="Screen Shot 2022-12-31 at 6 36 42 PM" src="https://user-images.githubusercontent.com/515597/210126373-7d437461-92ad-42fb-9d9b-4fd039c316d0.png">

As you can see, the ride side pane shows the note name in lowercase, while the left pane (which uses `dir_tree`) shows the note names capitalised correctly.

Given the way I'm using note names here, having them in lowercase does look rather odd.  Could you possibly fix that?

**Comment by dwrolvink** [comment]
Good find, because there is a _whole_ system to determine the node name and this old code was just using the lowercased filepath.

I've switched the name selection to the new system, nice thing about this is that if you'd like to overwrite the name for a page in the graph and tag view, then you can set it using the `graph_name` note setting, see:

- https://obsidian-html.github.io/Configurations/Note%20settings/Note%20settings.html#!graph_name
- https://obsidian-html.github.io/Configurations/Features/Graph%20view.html#!overwrite-the-name-of-a-note-in-the-graph-view


While I was busy I also checked the dirtree and tagpage implementations, and changed those as well to use the system used for the notes themselves.
