### ISSUE TITLE
Image not found if you add a width to the link

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#515]
I've come across a weird issue -- in my site, I'm trying to include an image with the following link:

```
![[profile_image|400]]
```

This displays fine in Obsidian itself, and the obsidian-html [documentation](https://obsidian-html.github.io/Demonstrations/Parsing%20Images%2C%20videos%2C%20and%20audio.html#!obsidian-type-image-links) suggests this is supported.  But when generating the site, the image file is not included.

If I remove the `|400` from the image link, it works.  I'm using ObsidianHTML version 3.3.1, downloaded from the main branch.

Is something broken in that version, perhaps?

**Comment by Gewerd-Strauss** [comment]
It might be that images containing any kind of `|stuff here` within the structure`![[link]]` is broken. In my case (#516), giving an image a title has the same effect. 

Could you please try and check if the resulting markdown file has error-messages at your image embeds, and post them here? 


This evening I'll try and pin down if the images get included if I don't provide bar elements). 

However, I am dealing with a variety of different, potentially nonexclusive bugs over the past couple dozen test runs I've performed, so it's extremely hard to figure out what is actually happening.

**Comment by dwrolvink** [comment]
So not sure why this keeps breaking, or how it could've worked before, though I recall implementing this and it working.

The last change was that we write a `<img src="link" width="200">` to the markdown file instead of the normal `![](link)` to retain the width information.

But.. there is no code to parse img tags at all in the md-->html step :confused: 
Anyways, added it and now it works for me, but still really scratching my head how I could've done the previous change and not have it working.

Anyways try out the latest version.

Adding #517 to the list to ensure this will not break again.

**Comment by Gewerd-Strauss** [comment]
> The last change was that we write a \u003Cimg src=\"link\" width=\"200\"> to the markdown file instead of the normal ![](link) to retain the width information

Does that mean that normal markdown syntax is thus not supported anymore? Or will there be an option to always convert to  `![](link)`-syntax? That would be really weird, because some markdown processors (notably rpandoc) do not support img src's.


I'm confused.

**Comment by dwrolvink** [comment]
I thought the markdown spec included (a handful of) html tags as supported to be used in between the markdown code.
I did not know that some tools can't deal with it, specifically not the img tag.

I could add a setting to disallow the creation of html tags in the markdown intermediate. In that case when running note-->md conversion, width and title information will necessarily be lost.

Let me know if that's something you would use.
Current workaround would be to remove width and title information from your image links in obsidian, this should result in just a normal `!()[]`

Btw using `[[link|image title]]` is not supported in Obsidian, see: https://help.obsidian.md/How+to/Format+your+notes#Images

If you want to add image titles, you should use `![image title](link)` in Obsidian.

**Comment by Gewerd-Strauss** [comment]
I stand corrected technically, so disregard the mention of rpandoc. It notably never worked for me, even with hand-written syntax as per documentation right now, but apparently it will work. 

> Btw using [[link|image title]] is not supported in Obsidian

Huh, alright. I think that means I got to hunt down whatever plugin/theme/whatever is causing this to work on my end. Apologies, disregard. (Note: It's the [Shimmering Focus](https://github.com/chrisgrieser/shimmering-focus) theme that does this on my end. It's amazing, and I sometimes forget that it heavily alters appearances. Again, sorry.)

This however poses a bit issue. As such link formatting _is_ supported by obsidian for normal links after all, and via the theme it is deeply ingrained in my workflow.

---

> I could add a setting to disallow the creation of html tags in the markdown intermediate. In that case when running note-->md conversion, width and title information will necessarily be lost.
> 
> Let me know if that's something you would use.

This would be useful. The assumption here is that you are converting to markdown instead of html so you can postprocess it elsewhere - use pandoc, just cuz you need normal md, whatever.

Suggestion on that assumption: Given the user is likely to go through the combined `.md`-file anyways, maybe cut out the information and paste it to a newline below. This way, removal by the user is really fast cuz you can just delete the line, and the data is preserved for those who need it - like when you are pandoc'ing to word, and _do_ need your image titles.


---

> Current workaround would be to remove width and title information from your image links in obsidian, this should result in just a normal !()[]

I suppose I'm gonna write an ahk script for image conversion then, cuz that is too ingrained in my workflow. Not sure if it is even doable at scale because I have no clue whatsoever how to parse embedded notes for their images now :P 

The technically best solution would be to ask for this to be an optional conversion step, but then again it is not exactly standard syntax - just cuz there's _a_ theme and a plugin doing this. 

(You would do me a huge favour if you could include a means of parsing and converting this specific syntax as outlined above. However, I know it's a super niche request given the circumstances, but I'd assume that it is substantially easier in a tool that is already capable of parsing obsidian files and embedded-therein notes, instead of somehow figuring out how to write an entire parser for note transclusions myself. But I am fully aware that I am just politely asking.)

In that case,  

    ![[link|image title]]
    ![[link 2]]
    
would become

    ![image title](link)
    ![](link 2)

**Comment by dwrolvink** [comment]
Made a new issue because this is getting out of scope for this specific issue. Let's continue there.

**Comment by dwrolvink** [comment]
Closing because the issue listed is fixed.
No feedback, but it works on my computer so whatever :)
