### ISSUE TITLE
Allow syntax ![[link|alt text]]

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#520]
I stand corrected technically, so disregard the mention of rpandoc. It notably never worked for me, even with hand-written syntax as per documentation right now, but apparently it will work. 

> Btw using [[link|image title]] is not supported in Obsidian

Huh, alright. I think that means I got to hunt down whatever plugin/theme/whatever is causing this to work on my end. Apologies, disregard. (Note: It's the [Shimmering Focus](https://github.com/chrisgrieser/shimmering-focus) theme that does this on my end. It's amazing, and I sometimes forget that it heavily alters appearances. Again, sorry.)

This however poses a bit issue. As such link formatting _is_ supported by obsidian for normal links after all, and via the theme it is deeply ingrained in my workflow.

---

> I could add a setting to disallow the creation of html tags in the markdown intermediate. In that case when running note-->md conversion, width and title information will necessarily be lost.
> 
> Let me know if that's something you would use.

This would be useful. The assumption here is that you are converting to markdown instead of html so you can postprocess it elsewhere - use pandoc, just cuz you need normal md, whatever.

Suggestion on that assumption: Given the user is likely to go through the combined `.md`-file anyways, maybe cut out the information and paste it to a newline below. This way, removal by the user is really fast cuz you can just delete the line, and the data is preserved for those who need it - like when you are pandoc'ing to word, and _do_ need your image titles.

---

> Current workaround would be to remove width and title information from your image links in obsidian, this should result in just a normal !()[]

I suppose I'm gonna write an ahk script for image conversion then, cuz that is too ingrained in my workflow. Not sure if it is even doable at scale because I have no clue whatsoever how to parse embedded notes for their images now :P 

The technically best solution would be to ask for this to be an optional conversion step, but then again it is not exactly standard syntax - just cuz there's _a_ theme and a plugin doing this. 

(You would do me a huge favour if you could include a means of parsing and converting this specific syntax as outlined above. However, I know it's a super niche request given the circumstances, but I'd assume that it is substantially easier in a tool that is already capable of parsing obsidian files and embedded-therein notes, instead of somehow figuring out how to write an entire parser for note transclusions myself. But I am fully aware that I am just politely asking.)

In that case,  

    ![[link|image title]]
    ![[link 2]]
    
would become

    ![image title](link)
    ![](link 2)

_Originally posted by @Gewerd-Strauss in https://github.com/obsidian-html/obsidian-html/issues/515#issuecomment-1368837598_

**Comment by dwrolvink** [comment]
I could add this logic:
```
with obsidian image tag of "![[link|title]]"

test if "|" is in obsidian image tag:
  --> false: return "![](link)"
split on "|" so we get data="title"
test if data is int:
  --> true: return '<img src="link" width="data"/>'
  --> false: return ![data](link)
```

That way, if you have `![[link|200]]` it will give `<img src="link" width="200"/>`
And if you have `![[link|blabla]]` it will give `![blabla](link)`

I think that should implement your usecase quite nicely.
Seeing how Obsidian is fine with your syntax and a popular *award-winning :trophy:* plugin uses it, it's no problem to incorporate this into obsidianhtml.

**Comment by Gewerd-Strauss** [comment]
> I think that should implement your usecase quite nicely.

Yes it does. I rarely use image sizing because md is too limited for styling outputs via pandoc for my  needs, so I have to do a cleanup run resizing shit anyways whenever I do so. However, the less time I have to have MS Word running, the happier I am :P (I _hate_ that program with a passion.)

Thank you.

**Comment by sevmonster** [comment]
I just started looking at the code, was this already implemented? Related https://github.com/obsidian-html/obsidian-html/pull/592

**Comment by Gewerd-Strauss** [comment]
> I just started looking at the code, was this already implemented? Related https://github.com/obsidian-html/obsidian-html/pull/592

Well, it is certainly working already - thankfully.
This is valid and gets parsed correctly:

    ![[FA2022_TLevelsInMaleMice_v7.png|Testosterone-concentrations [ng/mL] in male mice blood-serum after 10 weeks of exposure. Plotted are individual samples for Treatment (filled circles) and control (empty circles), as well as the respective samples' mean concentrations (Treatment: continuous line, Control: dashed line). Aside from one outlier, the testosterone concentrations are smaller in the treatment-group than in the control-group. The Treatment-mean is about 0.25 [ng/mL] lower than the Control-mean.|200]]
    

It should be noted that it will return the following result:

    <img src="001%20assets/FA2022_TLevelsInMaleMice_v7.png"  width="200" alt="Testosterone-concentrations [ng/mL] in male mice blood-serum after 10 weeks of exposure. Plotted are individual samples for Treatment (filled circles) and control (empty circles), as well as the respective samples' mean concentrations (Treatment: continuous line, Control: dashed line). Aside from one outlier, the testosterone concentrations are smaller in the treatment-group than in the control-group. The Treatment-mean is about 0.25 [ng/mL] lower than the Control-mean." title="Testosterone-concentrations [ng/mL] in male mice blood-serum after 10 weeks of exposure. Plotted are individual samples for Treatment (filled circles) and control (empty circles), as well as the respective samples' mean concentrations (Treatment: continuous line, Control: dashed line). Aside from one outlier, the testosterone concentrations are smaller in the treatment-group than in the control-group. The Treatment-mean is about 0.25 [ng/mL] lower than the Control-mean." />


So you might have to be able to parse src's if you want to be able to postprocess it, depending on whether or not src's are supported for whatever you are doing.

![grafik](https://user-images.githubusercontent.com/80548781/218313447-e2613e87-d9fa-47f9-b63a-456f28691cf2.png)
This is the result of my own automation script that automates ObsidianMD-Syntax → RMD-Syntax → Pandoc-Conversion → html/docx/pdf/..., with easy modification of output formats and most stuff you could think of. You can see that both the width-argument, as well as the figure caption were implemented correctly.  Note that due to the implementation, and lack of designated alt-text-field in the original format, the alt-text will have the same contents as the figure caption. For me, this is great, but others might need more control - in which case you will have to post-process the output yourself.


---

As you can see, the current implementation allows for quite a few weird symbols in the alttext/title. Note that there are probably a few edge-cases that have been missed, and a good amount of cases that are technically supported, but not legal under markdown-specs or the specs of whatever markdown-flavour you end up using.

**Comment by dwrolvink** [comment]
No weird symbols for me
![image](https://user-images.githubusercontent.com/30291690/218315231-03f345e9-5cc6-43f8-aec4-ea71893a1a12.png)

Further processing by other tooling is out of scope and the responsibility of the person choosing to use that tooling.

I'll close this as the described feature is implemented.

**Comment by Gewerd-Strauss** [comment]
> No weird symbols for me
> Further processing by other tooling is out of scope and the responsibility of the person choosing to use that tooling.

I know. The intention of the image, and my comment in general was just to point out to @sevmonster  that the format given is already recognised and translated properly - identifying width vs. title-strings, and assigning them correctly. 

The rest is then the user's responsibility.
