### ISSUE TITLE
Inline titles

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#531]
As of Obsidian 1.0, there are native inline note titles similar to those provided by the now [deprecated](https://github.com/mgmeyers/obsidian-embedded-note-titles) "embedded note title" plugin, however, obsidian-html does not appear to support them the same way...

**Comment by dwrolvink** [comment]
Yes I've noticed this, I've been a bit lazy in implementing/recording this change.

I thought I was being clever, building in a check whether the embedded note title plugin was installed or not, to enable this feature, and then they went ahead and put it in the core :sleeping:

So just cutting out that code and making it a simple toggle should suffice.
Perhaps I can read out the obsidian app.json for the `showInlineTitle` key to keep the semi automatic behavior, just have a toggle to completely turn it off if wanted in Obsidian but unwanted in the html output.

**Comment by dwrolvink** [comment]
Okay, so now the config setting `toggles/features/embedded_note_titles/enabled` will solely decide whether to include embedded titles or not. Meaning that by default the embedded title will be added (like how it is the default in Obsidian).

To disable it globally, set:
``` yaml
toggles:
  features:
    embedded_note_titles:
      enabled: False
```

The rich configuration options have fallen off the cart with this change. But it should be pretty easy to add back in via the config yaml (instead of reading it in automatically like was the case before this change).

I chose for this because otherwise there will be some annoying control logic comparing the built-in embedded titles feature with the embedded note plugin, and to avoid testing hell, we'll just have a flat list of config option in our own config yaml.

**Comment by dwrolvink** [comment]
added a setting to not add the embedded title if the note starts with an h1 header.

https://obsidian-html.github.io/Configurations/Features/Embedded%20note%20title.html#!disable-if-note-already-has-a-title
