### ISSUE TITLE
Mermaid diagrams not working

### ISSUE THREAD

**Issue by dbraun31** [obsidian-html/obsidian-html#535]
I'm having trouble getting mermaid diagrams to render correctly. I've never used these diagrams before, so maybe I'm missing something obvious. But trying to implement exactly as shown in the example in the docs:

```
# Testing Mermaid Diagrams

 \``` mermaid
  flowchart LR  
    Start --> Stop 
 \```
```

Gives the following html:

![mermaid](https://user-images.githubusercontent.com/22179795/211398740-ffa5ac93-177f-4b00-9c95-a39349b0516a.jpg)

See live version [here](https://davebraun.net/gaita/ideation/structured/html/test-mermaid.html). See md code [here](https://github.com/dab414/risky-visual-search/blob/master/ideation/structured/md/test-mermaid.md).

**Comment by dwrolvink** [comment]
Hi dab, yoy need to remove the backslashes, those are only there because otherwise things go wrong with parsing in the code block.

I will edit the docs today, I recently learned that you can wrap three backticks with a four backtick block so that should solve the issue on my side of having to add backslashes. 

Let me know if it works when you remove thw backslashes

**Comment by dbraun31** [comment]
That works! Thank you.
