### ISSUE TITLE
Inline tag placeholder not replaced when embedding notes

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#540]
In ConvertVault.py:289 there is a check that makes sure that we only replace tag placeholders if the note actually has tags. 

When another note is embedded, it will have the inline tag placeholders, and the tags attached, but only the note contents are inserted into the parent note, not the tags.

Should add an extra step to find an replace all inline tag placeholders, regardless of whether the note has tags or not.

**Comment by Gewerd-Strauss** [comment]
> ConvertVault

If this means that you are assuming that this problem should not occur when converting just a single note, I will unfortunately have to note that this might still happen when converting a single note. I have written a reference test file[^1] today because I need to create a couple of word-templates, and just now noticed that tags are not replaced:
![grafik](https://user-images.githubusercontent.com/80548781/213568362-136b52ea-195b-4939-b6e7-081518eca0de.png)

(Unrelated, but I was also pleasently surprised that unicode is not wrecked c:)
I have now found a couple of issues, some of which are definitely on OHTML's side, and some I will try and isolate before escalating further - as there are a couple of places which could be at-fault. 

[^1]:Aka, a note containing every possible form of syntax valid in Obsidian, so that I can then make a word-template for writing manuscripts according to a scientific journal's formatting guidelines.

**Comment by dwrolvink** [comment]
Inline tags are not supported in proper markdown, so if you use `note->md` and then do your own thing, i.e. convert the outputted md to html yourself, then the tag will be not removed indeed.

The whole purpose of the `{_obsidian_pattern_tag_tag}` line is to persist the inline tags from `note---->html`. That necessitates breaking the proper markdown output. For this reason you can disable inline tags via the config, but I'm guessing you don't want to do that.

Replacing the tags yourself is easy enough though, the markdown files should have a frontmatter blog with all the tags, and then just loop over those and replace each `{_obsidian_pattern_tag_<current_tag>}` instance with your inline tag block if it occurs.

**Comment by Gewerd-Strauss** [comment]
> Inline tags are not supported in proper markdown

Oh I didn't know that. Thank you. Yea that's pretty easy to fix then thankfully, given OHTML does all the hard parts of the job. 
Quick question, does it always output to

```
tags:
  - XX
```

Format? Even if only a single tag is found? Or does it then go to

```
tags: XX
```

instead? Might just as well ask now instead of in twelve hours.

**Comment by dwrolvink** [comment]
Did some tests, and these are the possibilities:

no inline tags set, and no tags in frontmatter, will give output:
``` yaml
---
tags: []
---
```

empty tag list set in frontmatter, will give output:
``` yaml
---
tags: []
---
```

when settings this in frontmatter by hand:

``` yaml
---
tags: tag
---
```

will give output:

``` yaml
---
tags:
- tag
---
```

when having no frontmatter and an inline tag like:

``` md
#inline_tag
```

will give output:

``` yaml
---
tags:
- inline_tag
---
```

and for completeness... when settings this in frontmatter by hand:

``` yaml
---
tags: tag tag2
---
```

will give output:

``` yaml
---
tags:
- tag2
- tag
---
```

So the output as compiled will always be either `tags: []` or 
``` yaml
tags:
- tag
- ...
```

**Comment by Gewerd-Strauss** [comment]
That's perfect, thank you very much.
