### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by zubayrali** [obsidian-html/obsidian-html#560]
Hello,

The search functionality is not working on my published site [zubayrrr.github.io](https://zubayrrr.github.io/), I updated obsidian-html using `pip install obsidianhtml` and it updated to the latest, I am also using the newest config options (`obsidianhtml export default-config`) but when I am trying to build it's throwing `RecursionError: maximum recursion depth exceeded in comparison` for a few files. I've checked these files, nothing looks out of the ordinary.

Also, it's taking quite a while to build(I've +1500 .md files in my vault)...like +20 minutes; is this normal?

Thanks

**Comment by zubayrali** [comment]
Update 1: So I am still not sure what was causing the issue but I've removed transclusion(`![]`) and also backlinks that mention the file itself **only** from the notes that were causing the build to fail and now it is building successfully but its excluding many files from some directories.

**Comment by zubayrali** [comment]
Update 2: So, it was not processing all of the files because  `process_all:` was set to `False`. It is now building everything except for search, it is not working even with the latest config options :(

Also, it took 11m 18s this time around.

**Comment by dwrolvink** [comment]
So just turning search functionality off made the compile go from >20 minutes to 11?

Obsidianhtml is not really designed for speed. I have just piled up features over time and there are a lot of inefficiencies there, but I have little time to really optimize the package. There should be a lot to win in performance.

20 minutes is extremely long, but 1500 pages is also pretty large. You might get some speedup by setting `copy_vault_to_tempdir: False`
> Note: I strongly advice to backup your vault before running obsidianhtml with that setting, because some features write into the vault and that thus may cause data loss if you are unlucky. 

It's still not very clear to me what issue you are running into. Could you post the full error output? What do you mean with "and now it is building successfully but its excluding many files from some directories."  ?

**Comment by dwrolvink** [comment]
Ahh I see when I go to your website the following:

![image](https://user-images.githubusercontent.com/30291690/215179748-6d1db37b-bbb1-4ece-bdb5-03a638d3b181.png)

This error comes from:
``` js
window.localStorage.setItem('search_data', data);
```

This means that, since your vault is so large, the search data is just too much to store in the localStorage of the browser. I did not anticipate that this could happen.

**Comment by dwrolvink** [comment]
sweet mother of christ :laughing: 

![image](https://user-images.githubusercontent.com/30291690/215180342-fcefdc4d-b3db-4099-9d42-9a115a39ee61.png)

**Comment by dwrolvink** [comment]
Do you have your vault itself on github too? This would be a very valuable input to improve obsidianhtml with.

**Comment by zubayrali** [comment]
Okay so, I didn't realize that `process_all` was set to False which is why I think it was excluding some of the files, for example, the /archive folder has +400 files but it was only building 16 files. Anyway, this issue was resolved by changing the option to True.

I didn't turn off the search functionality, it isn't working for me( I can't recall how long I've been facing this issue, but at one point it was working when I first started out with obsidianhtml), so yeah I dont know what caused it to go from 20m to 11m. I dont really mind the build time tbh, although I am looking into using obsidianhtml on github actions.

Heres my vault: [github.com/zubayrrr/wiki](https://github.com/zubayrrr/wiki) it had made it private ever since I started using obsidianhtml.

Thanks for looking into this. You're the best.

**Comment by zubayrali** [comment]
> Ahh I see when I go to your website the following:
> 
> ![image](https://user-images.githubusercontent.com/30291690/215179748-6d1db37b-bbb1-4ece-bdb5-03a638d3b181.png)
> 
> This error comes from:
> 
> ```js
> window.localStorage.setItem('search_data', data);
> ```
> 
> This means that, since your vault is so large, the search data is just too much to store in the localStorage of the browser. I did not anticipate that this could happen.

I thought so, as I tested it by excluding some of the folders and the search was just working fine. Phew, at least we know whats wrong.

**Comment by dwrolvink** [comment]
Good news is that this is fixable, bad news is that it is going to take some time to get right.

Since there is no server to work with, the javascript calls now just default to reading in the entire search data json. 
To avoid having to load this massive file every single time, it is stored in localStorage.

Some numbers to get an idea:
```
1.9M    output/html/obs.html/data/search.json.gzip
6.5M    output/html/obs.html/data/search.json
```
The max allowed storage in most browsers is 5M. 

If I cut out some weight (I know some data is duplicate because I am a ~~lazy~~ iterative coder). I think I could bring it below 5M, but that is just waiting until your vault grows larger and we have the same issue a year from now.

I don't think chunking makes any sense here, because we want to search in the entire vault. I could remove the preview. That is everything underneath the title of the note:
![image](https://user-images.githubusercontent.com/30291690/215200615-3bfea025-c93d-4e7a-a3bf-4fabd0e03eaa.png)

If I remove that, I can just be left with unique words of each note, instead of storing the entire note in the search data so as to be able to show the actual sentences. 

So some ideas for moving forward:

- Just store the zipped data in localStorage, that fits easily, and unzip it on every page load into just a variable instead of localStorage.
  - Test to see whether this is workable
- Remove the keywords , since we now have the entire contents to search through
  - Did this just now, that makes the file `4.7M    search_min.json` would fix your issue at the moment, but not much wiggle room. Will do this regardless because it would be a big improvement.  #563 


Btw I just converted your entire vault with `process_all: True` and this was the time:
```
416.45s user 54.83s system 99% cpu 7:55.16 total
```
So about 8 minutes for me. I have quite a beefy CPU so that seem comparable to your setup.
You can see also that the CPU was near 100% busy, so running any taxing processes alongside the conversion might explain why you got 20 minutes in one run.

The second pass html phase is what takes most of the time, so I'll start looking whether I can get any performance win there. I'm guessing there is some combinatorial explosion going on there.

**Comment by zubayrali** [comment]
Thank you very much for looking into this and also for breaking down the problem for me.

I am closing this issue now but just so you are aware, the original reason for me to open this issue was because of this error `RecursionError: maximum recursion depth exceeded in comparison` which I think is caused when a note is backlinking to itself.

Thanks again

**Comment by dwrolvink** [comment]
check out #564 
if you update now search should work out of the box, though perhaps a bit sluggish

**Comment by dwrolvink** [comment]
Last update:

With the latest changes, running under python3.11 it now takes me 46 seconds to compile your vault, down from around 8 minutes, even with the dir_tree feature on. With python3.10 it takes about 54 seconds, so also a mayor improvement there.

I'd say try out the latest master code :)
I'll leave it at that for now.

**Comment by zubayrali** [comment]
woah I just tried it out, its much much faster now. Search is also not sluggish anymore.
Thanks <3
