### ISSUE TITLE
Inserting a code block or callout in ordered list resets the numbering

### ISSUE THREAD

**Issue by indcyfa** [obsidian-html/obsidian-html#585]
If you insert a code block (or callout) between two ordered list items obsidian-html generates a new list. According to https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list/22138846#22138846 inserting 4 space character before the code block should prevent this however it doesn't work.

**Desired output:**

1. item 1
2. item 2
```
Code block
```
3. item 3

**Produced output:**

```
<or>
<li>item</li>
<li>item </li>
</or>
<div class="codehilite">Code block</div>
<or>
<li>item </li>
</or>
```

**Comment by dwrolvink** [comment]
For this input I get the desired output:
``` md
1.  item 1
2.  item 2

        Code block

3.  item 3
```
Note: 
- The newlines before and after the codeblock, these are required
- 8 preceding spaces to the code block
- It needs to be an indented codeblock as shown here, not a fenced code block


Output:
``` html
<ol>
  <li>a   </li>
  <li>
    <p>b   </p>
    <div class="codehilite"><pre><span></span><code>run()</code></pre></div>
  </li>
  <li><p>c</p></li>
</ol>
```

![image](https://user-images.githubusercontent.com/30291690/218140473-fc35279c-0d28-4afa-abf0-1ae18bef1c92.png)

The reason this works, and not with fenced codeblocks is because we use python-markdown, and this package has this limitation. See also:
- https://github.com/Python-Markdown/markdown/issues/472#issuecomment-216226057
- https://github.com/Python-Markdown/markdown/issues/53

**Comment by indcyfa** [comment]
Thank you, removing the fencing worked! 

However I still can't get ordered lists to work with **call-outs**. Are there any workarounds?

**Comment by dwrolvink** [comment]
Alright, I have a fix, but it is pretty hacky, so I am expecting a lot of bugs.
I don't have enough creativity to find them all though.

At the moment I can get this output: 
![image](https://user-images.githubusercontent.com/30291690/218203048-9642e742-727f-428a-aaca-169250dbb425.png)

With this input:
``` md
1.  item 1
2.  item 2
  >[!test]- bla
  > test
3. item 3

vla
> [!test]+ bla
> bla
>   >[!test]- bla
>  > test

```

You can install the latest code and try it out.
Very interested in any bugs you might find!

**Comment by indcyfa** [comment]
It works, thank you! The main bug is that the contents of the callout have no margin/padding, I think its lacking a `<p>` tag.

<img width="931" alt="Screenshot 2023-02-11 at 10 24 27" src="https://user-images.githubusercontent.com/90133555/218250791-79b1f4b0-6f6b-41e6-9805-bd528dba8b47.png">

**Comment by dwrolvink** [comment]
Weird, I do not have this issue, what is your exact input (content of the note)?

**Comment by indcyfa** [comment]
```
1. Item1.
> [!Warning!]
> This is a warning.
2. Item 2
```
I don't have any custom stylesheets, using documentation theme.

**Comment by dwrolvink** [comment]
So, that took quite a deep dive into the wonderous world of python-markdown, but it turns out that if we are in a list tree, then the ParagraphProcessor will just return plain text instead of wrapping stuff in `<p>` tags.

Made a fix and some code tweaks, any use case I can imagine now works pretty well for me.

Nice added benefit of this change is that now callouts can contain callouts, which is pretty out there, but Obsidian makes a point about that *cool feature* on their help page so nice that I got it working too :rofl:

**Comment by indcyfa** [comment]
Amazing! However, I can't get it to work on the markdown I posted above. I used pip to install latest master branch, commit `e84e1eb` and cleared browser cache. Can you confirm it works for you on the exact markdown I posted above?

**Comment by dwrolvink** [comment]
I get this:
![image](https://user-images.githubusercontent.com/30291690/218319303-71ff52b6-cf95-49bc-afaf-be2a5aee076d.png)

From this:
``` md
1. Item1.
> [!Warning!]
> This is a warning.
2. Item 2
```
![image](https://user-images.githubusercontent.com/30291690/218319320-b7d73a0a-eeed-44d8-a8d7-6acd591e00b0.png)

Did you run the uninstall too?

You might try the following:
``` shell
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git --upgrade
```

When viewing your website, and it's still not working, could you right click on the corner of the callout, and select inspect, and then share the html that it shows you?

**Comment by indcyfa** [comment]
Reinstalling as per your instructions got it working, thank you for the quick responses!

**Comment by dwrolvink** [comment]
Nice! Closing this then, just post here if you find issues related to this.
