### ISSUE TITLE
v4.0 html_url_prefix not working for me.

### ISSUE THREAD

**Issue by cquenelle** [obsidian-html/obsidian-html#642]
I'm trying to set up a new config file that works in v4.0 and gives me what was working on v3.

I have:
```
html_url_prefix: '/betatest'
html_output_folder_path_str: 'output/html/betatest'
```

The html files end up in the right spot, and the links are created correctly, but the web server is not hosting from the top where it should:
OBSHTML: Started webserver at http://localhost:8888/ hosting from /Users/cquenell/Desktop/Projects/SW/MyStuff2023/output/html/betatest (Ctrl+C to exit)

I think I'm expecting the web server to start hosting from the directory above my html_url_prefix

**Comment by dwrolvink** [comment]
I just noticed that `obsidianhtml run` does not work together with the modules at all still. So for now maybe best to use `convert` exclusively:

``` bash
python -m obsidianhtml convert -i path/to/config.yml
```

and in another terminal, run this:
``` bash
cd /Users/cquenell/Desktop/Projects/SW/MyStuff2023
python -m obsidianhtml serve --directory output/html
```

You can keep the second terminal running this way and it will keep hosting the website locally. If you'd cd to output/html directly, the folder would get deleted upon a new run of the program, and the server would stop working as expected.

For the issue of `run` not hosting the correct folder, I could add a check whether the output folder is named the same as the html_url_prefix, and then host the parent of the html output folder instead of the html output folder itself.

**Comment by cquenelle** [comment]
Your suggestion would only work for one level of subdirectory right?
What if you added a new variable:

html_output_subdirectory_path_str='betatest'
and I set:
html_output_folder_path_str: 'output/html'

Or as an alternative you could add an explicit config variable for the argument to the web server that is only used for the web server.

**Comment by cquenelle** [comment]
Regarding avoiding the 'run' command and using two commands:
This works much better, thanks! I should have converted to that a long time ago!

**Comment by dwrolvink** [comment]
Great!

I am currently porting the `run` code to the module system, and I'm thinking to just step away from the `run` command all together with version 4.

I wrote it to have a quick way for new users to get a working config and exported vault, and be able to see it directly in their browser, but it adds complexity and many users get hung up on it when I actually would prefer everyone to just use `convert` instead. More trouble in the end than that it is worth.

The main usecase for `run` that I want to carry over is to set certain config values automatically and do thorough checking and clear error messages if anything is configured wrong.

So yeah I guess we can close this issue, seeing how the run command will be absorbed into `convert` anyways.
