### ISSUE TITLE
Colors and german umlauts (öäüÖÄÜß) in mermaid

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#675]
Here you see, that the font is not readable, because of lacking contrast:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/02ee60a2-ed6a-410c-876e-24b92d373ca6)

Also here:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/7b05cc12-e713-4e43-8719-991dff47f407)

---

Here you see (after I marked the text with the mouse) that the letter ä in the word "abändert" is not there.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/4ab9303d-8993-4b6a-abff-d1eeeef4cff0)

**Comment by dwrolvink** [comment]
Okay, so there is a piece of code to strip non printable characters, so that (through some magic) the set of characters that you end up with are `0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+, -./:;<=>?@[\]^_{|}~ `

This was done because some users had Cyrillic characters that broke the mermaid code.

I've added (in v4 only!) a toggle to turn this off/on.
I casually tested it with the page you gave and it seems fine in your case to turn it off.

 To turn the default behavior off, add this to your config.yml:
``` yaml
toggles:
  features:
    mermaid_diagrams:
      strip_special_chars: False
```

I've also added back in the mermaid.css file, not sure why I ever removed that. It doesn't really impact the look of the mermaid diagrams it seems.
I've added a harcoded `background-color: white` to avoid your dark theme issues, giving:

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/6acc2cd5-3346-4bdc-94fd-a4e135b0b204)

Bit wide, but setting `width: fit-content` messes with the mermaid generator, and then text will be hidden and other issues, so this is the best I can do currently.

**Comment by merlinuwe** [comment]
On my installed Google Chrome and Firefox:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/710bbbf5-ed60-4fec-a4fd-8005fb471c30)

Not perfect for a dark theme, but I don't want to be ungrateful. Thank you very much.

---

This is also ok:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/0cf8fc74-5df1-4c79-9fee-d5b0fcd00652)

(I think the ugly font in the legend is not your problem.)
