### ISSUE TITLE
external http anchor tags should use a target="_blank" so that clicks on them are launched in another tab/window

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#71]

**Comment by dwrolvink** [comment]
I read a hot take once that no link should use _blank because if a user wants to open a tab in a new page, they can just use middle mouse button or ctrl+click. The reason of making external links visible is partly so that you know you're leaving the garden of notes. 

But no need to debate if you can make it configurable.
Will make another issue for that
