### ISSUE TITLE
dataview support

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#715]
I don't think you can avoid implementing data view support.

One example:

![Image](https://github.com/obsidian-html/obsidian-html/assets/4138869/5e7e1107-ea96-4b1e-9f3c-5c1d0e203b1f)

And lot of tables and lists ...

Note that this will eventually be integrated ("Feb. 2023") into Obsidian.

When the time comes with an insider built, we can take another look, if you want.

**Comment by dwrolvink** [comment]
See also #271 

> I don't think you can avoid implementing data view support.

I can :)
 
Only way to properly integrate this, as far as I was able to tell, is to write a plugin for obsidian which exports all the tables and lists generated by dataview, and then load those in when compiling.

Very annoying multi-step process. But recreating the functionality is above my paygrade (capability even, probably), and the same counts for cloning the dataview plugin and creating a shim for the obsidian components. 

So all in all a giant task, one that I personally don't profit from, as I don't use dataview myself.
I have much time now because I am off from work, but in a week I am back at work and then I can surely not work on this.

> Note that this will eventually be integrated ("Feb. 2023") into Obsidian.

Feb 2023 is in the past, so it is already integrated? Couldn't find anything from a quick google.

**Comment by merlinuwe** [comment]
You are right, no trace. I swear, there was an announcement of this.
This should be the sucessor:
https://github.com/blacksmithgu/datacore

I understand that this is too much work for you.

**Comment by dwrolvink** [comment]
If anyone can find/create a port/shim/anything that can be easily tapped into with python at the compile step, then I will happily implement this btw. So open invitation to whoever reads this.

Closing this in favor of the older issue, we can continue the conversation there.
