### ISSUE TITLE
Formating of codes (here: linux output)

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#725]
This code in Obsidian

looks so in Obsidian view mode:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/cd0b8595-661f-441b-968e-417adabd7523)

or so with the customize code plugin:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/35165f35-ac29-49b1-9e0c-4293f98ec291)

and in the output:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/7b59d11a-efee-4177-b0e9-059db8f4875a)

The grey letters should be better readable. White would be a good choice, but a special syntax highlighing would be better.

"user" is blue formatted.

**Comment by blacklightpy** [comment]
In Markdown, you can do a certain level of syntax highlighting by adding the language directly after the backticks:

```
    ```bash

    <code here>

    ```
```

But that probably won't be of much help here since this is output, and not a script. However it could be worth a try.

EDIT: You could also try "plain text" to avoid syntax highlighting at all.

**Comment by dwrolvink** [comment]
The highlights are created by the codehilite plugin for python-markdown.

You can provide your own css to overwrite the way highlights are styled:
- https://python-markdown.github.io/extensions/code_hilite/#step-2-add-css-classes

Optimizing highlighting within obsidian-html is a bit out of scope for the project, so I won't change any of the default styles, even though I admit the default shell highlighting looks a bit wonky.
