### ISSUE TITLE
[Enhancement] For tables containing images, click to preview image in full size

### ISSUE THREAD

**Issue by blacklightpy** [obsidian-html/obsidian-html#728]
This is helpful for images in tables, which can be too small to see. Currently on PC, Ctrl+clicking the image does not open it in a  new tab. Right clicking and opening each image is not ideal.

Another implementation idea:
Tables with images need not restrict content width, and should be able to overflow towards the right.

**Comment by dwrolvink** [comment]
The tables overflowing to the right was the original behavior, but some users had issue with this, and it is not the obsidian behavior, which limits the screen width, so we decided to move to a fixed-width table, which is honestly also pretty much the standard when it comes to tables.

I did add in some js code that wraps any image in the note container in a link that points to its own src, so you can click and get the original size in a different tab.

This functionality is disabled when the image is already wrapped by a link element, because otherwise you'd get different behavior in the webpage than in obsidian.
