### ISSUE TITLE
Non-ASCII characters are not recognized as tags and become h1

### ISSUE THREAD

**Issue by H1rono** [obsidian-html/obsidian-html#743]
The following markdown is not converted as expected:

```md
# index

#📝

#タグ

#?-tag
```

In Obsidian, `#📝` and `#タグ` are recognized as tags and `#?-tag` are recognized as plain text.

<img width="162" alt="obsidian-tag-test" src="https://github.com/obsidian-html/obsidian-html/assets/54711422/5c22cb49-ae78-43ce-8762-887d4d22c00e">

But in obsidian-html, they are all recognized as `h1`.

<img width="1381" alt="obsidian-html-tag-test" src="https://github.com/obsidian-html/obsidian-html/assets/54711422/b0a448ad-71c3-47e1-9371-b788e9c93e79">

The problems are as follows:

- Non-ASCII characters are not included in the tag.
- `#` followed by no whitespace results in `h1`.

**Comment by dwrolvink** [comment]
Okay so for this spec:
https://help.obsidian.md/Editing+and+formatting/Tags#Tag+format

```
You can use any of the following characters in your tags:

    Alphabetical letters
    Numbers
    Underscore (_)
    Hyphen (-)
    Forward slash (/) for [Nested tags](https://help.obsidian.md/Editing+and+formatting/Tags#Nested%20tags)
```

I assumed the ascii definition of "letters" and "numbers"
Changed this to the full unicode definition.

Emoticons are not listed in the spec so this is another case of Obsidian not following its own spec.
I can confirm that emojis work though, so I added this in too.

Only the `#?-tag` is not yet fixed, as python-markdown turns this into a header, so it's more difficult to fix and you should not have this kind of text in your notes anyways. Otherwise you could always wrap the text in backticks.

This is fixed in master, not in the latest release, to test this code out, install the master branch:
- https://obsidian-html.github.io/v4/instructions/install-a-different-version.html#!install-master-branch

I hope this fixes it for you!
