### ISSUE TITLE
make a helper function to return config values

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#78]
this will be a clean way to handle if values are not configured in the config.yml

the helper function will set 'default' values for config.yml keys and if a specific value is requested that is not properly configured, will fall back to those default values OR will give an appropriate error to the end user to tell them to configure a key in their config.yml

**Comment by dwrolvink** [comment]
yes good idea
I was dubbing whether I could do a dict join: just have a fully filled in dict with default values and then overwrite it with the user provided values, but that won't catch typo's and can lead to severe headscratching.

Maybe a combination of a handler function that does the thing I just wrote, and also checks if new keys are created, and in that case raise an exception like "hey your config introduces a key that I don't know of, you're probably making a typo here".

**Comment by dwrolvink** [comment]
Gonna do some testing / review on the code tonight because this is a major PR
Keep this issue open.

**Comment by dwrolvink** [comment]
1. Here you overwrite the user provided config with the default config, where I think we should do it the other way around:
- get default config
- get total amount of values (recurse over keys)
- default_config.update{}
- get total amount of values again
- bug out if more values are found then before (and show which settings those are)
2. the `if v` in the dict comprehension (L:378) makes it so that html_url_prefix is entirely removed from theConfig if the value is an empty string, which should be a valid option
https://github.com/obsidian-html/obsidian-html/blob/2ac4f61626076d6ad1ba69fd171a79b31f3bb4ee/obsidianhtml/__init__.py#L364-L378 

3. I do like using a function call to fetch the config ad-hoc, but the fact that it uses an scope global is very bad practice in Python, can be very buggy. Perhaps we should refactor it to pb.gc() or something, so the config from the quasi-global object is used instead of using the scope global of theConfig.

**Comment by dwrolvink** [comment]
Okay so I made what looks like a huge overhaul, but it's actually minor compared what you introduced, @jcolson 

For one: I expanded out the merge code, because I really wasn't sure how to reason about how the merge worked before. For example: what happens when a user makes a string of a dict? I already had an issue with html_url_prefix being an empty string causing it to be removed.

I also flipped the idea around a bit. The default_config has ALL the valid keys. The user cannot create any new keys, at any place (without also changing the default config, but at that point the user is a coder). This allows us to easily test for typos and indentation errors, which, going by experience, happen a LOT.

So because default config has all the values, and all the defaults, it is simply overwritten by the user-provided config at a recursive key-by-key basis. If a value for a key does not have the same type as the default config, the program will bug out. This way you can't overwrite a dict with a string or something similar.

To implement the "this is a value that is required to be filled in by the end user" case, all the required keys have the value `'<REQUIRED_INPUT>'`, and then we just recurse over all the values after the merge is done to find any missing input. This is nice because we can use the default_config as a visual aid of what must be a minimal config yaml.

Talking about that, I added the commandline option of `-gc` to output default_config, for when someone is troubleshooting his own config.

The other part is that I moved some minor functions out of__init__.py into lib.py, because the former is long enough as it is :)

I hope I didn't break too much, double check / code review would be much appreciated.

**Comment by jcolson** [comment]
looks like we lost the ability to not pass any parameters

```
obsidianhtml 
ERROR: No config file passed in. Use -i <path/to/config.yml> to pass in a config yaml.
[Obsidian-html]
- Add -i </path/to/input.yml> to provide config
- Add -v for verbose output
- Add -h to get helptext
- Add -eht <target/path/file.name> to export the html template.
- Add -gc to output all configurable keys and their default values.
```

and html_custom_inclusions is gone now as well
```
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 398, in main
    pb.loadConfig(input_yml_path_str)
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/PicknickBasket.py", line 39, in loadConfig
    self.config = self.MergeDictRecurse(default_config, input_config)
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/PicknickBasket.py", line 66, in MergeDictRecurse
    raise Exception(f'\n\tThe configured key "{key_path}" is unknown. Check for typos/indentation. {helptext}')
Exception: 
        The configured key "html_custom_inclusions" is unknown. Check for typos/indentation. 

Tip: Run obsidianhtml -gc to see all configurable keys and their default values.
```

and
```
> COPYING VAULT /Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook TO /var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpcihfvczp < DONE
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 523, in main
    theConfig['md_entrypoint_path_str']  = str(index_dst_path)                              # should not be used anymore at this point, but just to be sure
NameError: name 'theConfig' is not defined
```

i'll create another PR for those

**Comment by dwrolvink** [comment]
But what should the obsidian_vault input be if you didn't pass in any input? Just the folder that you're in?
And what would be the entrypoint note then?

It would make sense to read a system variable if no input is givien, but I don't see how you could go without passing in any config one way or another.

**Comment by jcolson** [comment]
> But what should the obsidian_vault input be if you didn't pass in any input? Just the folder that you're in? And what would be the entrypoint note then?
> 
> It would make sense to read a system variable if no input is givien, but I don't see how you could go without passing in any config one way or another.

#57 --- had done this already ;-)  #94 has it again

**Comment by dwrolvink** [comment]
ah you just assume config.yml is in the folder you're in, fine enough
perhaps reading an env var as fallback would be nice too, but that could also just be done via an alias, so that's far enough into the "nice to have realm" to not bother with it until someone has a real usecase for it.

**Comment by dwrolvink** [comment]
closing, I think this should resolve this issue.
gonna add a testcase for that create_index_from_tags/enabled: True case that I missed :)
